services:

  db1:
    image: postgres:15
    container_name: tweet_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_TWEET_PASSWORD}
      POSTGRES_USER: ${DB_TWEET_USER}
      POSTGRES_DB: ${DB_TWEET_NAME}
    ports: 
      - ${DB_TWEET_PORT}:5432
    volumes:
      - ./prisma/docker-data/db1:/var/lib/postgresql/data

  
  # db2:
  #   image: postgres:15
  #   container_name: auth_db
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_AUTH_PASSWORD}
  #     POSTGRES_USER: ${DB_AUTH_USER}
  #     POSTGRES_DB: ${DB_AUTH_NAME}
  #   ports: 
  #     - ${DB_AUTH_PORT}:5432
  #   volumes:
  #     - ./prisma/docker-data/db2:/var/lib/postgresql/data